[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  VITE_SUPABASE_URL = "https://aoqvffeqscehfnrjgjrs.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvcXZmZmVxc2NlaGZucmpnanJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwMjcyNDIsImV4cCI6MjA1MzYwMzI0Mn0.SSJzliR8-74Qmlnw-3IMIjRdzO1NoCgq2d9K9TqYKag"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
